### ISSUE TITLE
Ensure that no two drones can have the same date id

### ISSUE THREAD

**Issue by EliaGorokhovsky** [SaurabhTotey/Galactic-Rush#21]

**Comment by SaurabhTotey** [comment]
Closing because, as previously discussed, drones can be uniquely identified by owner id and creation time. The same owner can't make more than 1 drone at the same exact time. If we have automatic drone creation, we can put a `Thread.sleep(1)` for unique creation times when the owner id is the same. Otherwise, if two different players create drones at the exact same time, the owner IDs will be different.
